name:                essence-of-ad
version:             0.1.0.0
github:              "msakai/essence-of-ad"
license:             BSD3
author:              "Masahiro Sakai"
maintainer:          "masahiro.sakai@gmail.com"
copyright:           "2020 Masahiro Sakai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/msakai/essence-of-ad#readme>

dependencies:
- adjunctions
- base >= 4.7 && < 5
- containers
- pointed

library:
  source-dirs: src

tests:
  essence-of-ad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - essence-of-ad
    - tasty
    - tasty-hunit
